spring.jackson.time-zone=UTC

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ufanet
spring.datasource.username=ufanet
spring.datasource.password=ufanet

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=ufanet
spring.rabbitmq.password=ufanet

